// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojtlkrnomygrkaesrcvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qdGxrcm5vbXlncmthZXNyY3ZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczOTY2MzMsImV4cCI6MjA3Mjk3MjYzM30.Whl5JgCnlTRw8BNp1Ul9p6jv5GdmzmikXTtfn4qLdV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});